### PR TITLE
Move render check

### PR DESCRIPTION
**Pull request by xronos-i-am**
### Summary

Allows to add some additional checks to overrided `render?` method:

```ruby
def render?
  view_context.cookies[:show] == false
end
```

### CODE REVIEW

**Comment by joelhawksley** [comment]
@xronos-i-am thanks for the contribution!

Might you be able to include a test case that necessitates this change?

**Comment by xronos-i-am** [comment]
@joelhawksley done

**Comment by xronos-i-am** [comment]
@jonspalmer done

**Comment by joelhawksley** [comment]
👏 thank you for your contribution @xronos-i-am ❤️

**Pull request merged**
